/**
 * @description 导出 Peanut Cocos 业务插件作者面契约与模块基类。
 */
export { PluginModuleBase } from './plugin-module-base.js';

export type {
    DesignSourceCapabilityId,
    AssetCatalogBucket,
    IAssetCatalogClient,
    IAssetCatalogAssetDbSnapshot,
    IAssetDeleteClient,
    IAssetReadAssetSnapshot,
    IAssetReadAssetSubSnapshot,
    IAssetReadClient,
    IAssetWriteClient,
    ICanvasContext2D,
    ICanvasImage,
    ICanvasImageData,
    ICanvasService,
    ICanvasSurface,
    ICreatorVersionClient,
    IDesignSourceCapabilityDescriptor,
    IGrantedRuntimeClientSet,
    IMessageClient,
    IMcpCapabilityInvocation,
    IMcpCapabilityProgress,
    INativeCapabilityClientSet,
    IPanelBridgeClientFactory,
    IPluginActivateContext,
    IPluginEventBus,
    IPluginFileStorageApi,
    IPluginLogger,
    IPluginMcpApi,
    IPluginManagedTaskApi,
    IPluginTaskExecutorOptions,
    IPluginModule,
    IPluginNetworkClient,
    IPluginNetworkRequest,
    IPluginNetworkResponse,
    IPluginPanelApi,
    IPluginProtectedKeyApi,
    IPluginRegisterContext,
    IPluginRegistrationApi,
    IPluginRegistrationInput,
    IPluginServiceApi,
    IPluginStorageApi,
    IPluginTaskApi,
    IPluginTaskExecutorContext,
    IProjectReadClient,
    ISceneClient,
    ISelectionClient,
    McpCapabilityHandler,
    PluginManagedTaskRequest,
    PluginTaskExecutor,
} from './plugin-module-contracts.js';

export type { PluginDeactivateReason } from '@peanut/pod-protocol';
