// Generated by tools/generate-creator-profiles.mjs from specs/creator-profiles/creator-profiles.json.

/**
 * @description Creator 宿主使用的版本适配档案标识。
 */
export type CreatorProfileId =
    | 'creator-24'
    | 'creator-30-35'
    | 'creator-36-37'
    | 'creator-38';

/**
 * @description Creator 宿主 API 的主版本家族。
 */
export type CreatorHostFamily = 'creator-2x' | 'creator-3x';

/**
 * @description 当前版本档案具备的支持等级。
 */
export type CreatorProfileSupport = 'full' | 'experimental' | 'unsupported';

/**
 * @description Creator 版本画像的不可变运行时定义。
 */
export interface ICreatorProfileDefinition {
    /**
     * @description 档案标识。
     */
    readonly id: CreatorProfileId;

    /**
     * @description 档案覆盖的最小 Creator 版本。
     */
    readonly minVersion: string;

    /**
     * @description 档案不再覆盖的首个 Creator 版本。
     */
    readonly maxVersionExclusive: string;

    /**
     * @description 档案对应的 Creator API 家族。
     */
    readonly hostFamily: CreatorHostFamily;

    /**
     * @description 未命中实机证据时的默认支持等级。
     */
    readonly defaultSupport: Exclude<CreatorProfileSupport, 'full'>;

    /**
     * @description 已通过宿主实机验证的精确版本集合。
     */
    readonly verifiedVersions: readonly string[];

    /**
     * @description 允许在工程版本精确匹配时执行写操作的版本集合。
     */
    readonly writeEnabledVersions: readonly string[];
}

/**
 * @description 由版本画像规范生成的不可变目录。
 */
export const CREATOR_PROFILE_DEFINITIONS: readonly ICreatorProfileDefinition[] = Object.freeze([
    Object.freeze({
        id: 'creator-24',
        minVersion: '2.4.0',
        maxVersionExclusive: '3.0.0',
        hostFamily: 'creator-2x',
        defaultSupport: 'experimental',
        verifiedVersions: Object.freeze([]),
        writeEnabledVersions: Object.freeze([]),
    }),
    Object.freeze({
        id: 'creator-30-35',
        minVersion: '3.0.0',
        maxVersionExclusive: '3.6.0',
        hostFamily: 'creator-3x',
        defaultSupport: 'experimental',
        verifiedVersions: Object.freeze([]),
        writeEnabledVersions: Object.freeze([]),
    }),
    Object.freeze({
        id: 'creator-36-37',
        minVersion: '3.6.0',
        maxVersionExclusive: '3.8.0',
        hostFamily: 'creator-3x',
        defaultSupport: 'unsupported',
        verifiedVersions: Object.freeze([]),
        writeEnabledVersions: Object.freeze([]),
    }),
    Object.freeze({
        id: 'creator-38',
        minVersion: '3.8.0',
        maxVersionExclusive: '3.9.0',
        hostFamily: 'creator-3x',
        defaultSupport: 'experimental',
        verifiedVersions: Object.freeze(["3.8.3","3.8.7"]),
        writeEnabledVersions: Object.freeze(["3.8.3","3.8.7"]),
    }),
]);
