export type {
    IMcpCapabilityCatalog,
    IMcpCapabilityDefinition,
    IMcpAiHandlingGuidance,
    IMcpFailureDetails,
    IMcpJsonSchema,
    McpCapabilityRisk,
    McpCapabilityCategory,
    McpCapabilityExecutionLane,
    McpFailureCategory,
    McpFailureRecommendedAction,
    McpFailureState,
} from './mcp/mcp-capability-contracts.js';
export type {
    ICommandContribution,
    IDiagnosticsContribution,
    IMenuContribution,
    IPanelContribution,
    IPanelContributionPermission,
    IPanelDefaultSize,
    IPluginContributionManifest,
    IDesignSupporterContribution,
    PanelActivationPolicy,
    PanelPlacement,
    PanelSessionPolicy,
} from './contribution/contribution-contracts.js';
export type {
    IPanelBridgeClient,
    IPanelBridgeEnvelope,
    IPanelBridgeMessageHandler,
    IPanelBridgeRequest,
    IPanelBridgeRequestHandler,
    IPanelBridgeResponse,
} from './panel/panel-bridge-contracts.js';
export type {
    IAssetDbPermissionManifest,
    IBuildPermissionManifest,
    IFileSystemPermissionManifest,
    IGrantedPermissionSet,
    INativeCapabilityPermissionManifest,
    INetworkPermissionManifest,
    IPanelPermissionManifest,
    IPluginPermissionManifest,
    IShellPermissionManifest,
} from './permission/permission-contracts.js';
export type { IPluginError, IChangeSetEntry } from './result/result-contracts.js';
export type {
    ITaskBatchReceipt,
    ITaskCancelResult,
    ITaskReceipt,
    ITaskRequest,
    ITaskResult,
    ITaskSnapshot,
    ITaskTrace,
    ITaskTraceStep,
    TaskMergePolicy,
    TaskPriority,
    TaskScope,
    TaskStatus,
    TaskTraceStatus,
} from './task/task-contracts.js';
export type { CreatorPhase, ICreatorVersionInfo } from './cocos/creator-version.js';
export {
    CREATOR_PROFILE_DEFINITIONS,
    type CreatorHostFamily,
    type CreatorProfileId,
    type CreatorProfileSupport,
    type ICreatorProfileDefinition,
} from './cocos/creator-profile-catalog.js';
export type {
    ICreatorContext,
} from './cocos/creator-context.js';
export { CreatorPhaseResolver, type ICreatorVersionNumbers } from './cocos/creator-phase.js';
export type {
    EditorMcpActionId,
    EditorMcpExecutionLane,
    EditorMcpThinLayerAvailability,
    EditorMcpOperationId,
    IAssetCatalogLookupMcpInput,
    IAssetImportMcpInput,
    IAssetImportPlanMcpInput,
    IAssetManagedStatusMcpInput,
    IAssetQueryDependenciesMcpInput,
    IAssetReplaceReferencesMcpInput,
    IAssetWaitReadyMcpInput,
    IAssetScanMissingReferencesMcpInput,
    IAssetFindReferencingNodesMcpInput,
    IAssetOpenMcpInput,
    IAssetCopyMcpInput,
    IAssetMoveMcpInput,
    IAssetRenameMcpInput,
    IAssetCreateFolderMcpInput,
    IAssetDeleteMcpInput,
    IAssetReimportMcpInput,
    IAssetWriteTextMcpInput,
    IAssetWriteTextFileMcpInput,
    IAssetEnsureSpriteFramesBatchMcpInput,
    IAssetResolveMcpInput,
    IAssetSearchMcpInput,
    IAssetAuditUnmanagedWritesMcpInput,
    IAssetQueryPropertySchemaMcpInput,
    IAssetQueryInheritanceMcpInput,
    IAssetQueryCompatibleTypesMcpInput,
    IPreviewQueryMcpInput,
    IPreviewRefreshMcpInput,
    IPreviewQueryErrorsMcpInput,
    IPreviewCaptureMcpInput,
    ILumenLodRecalcBoundsMcpInput,
    IReferenceQueryImageMcpInput,
    IReferenceSetImageMcpInput,
    IBuilderQueryPlatformsMcpInput,
    IBuilderQuerySchemaMcpInput,
    IBuilderQueryDefaultConfigMcpInput,
    IBuilderBuildMcpInput,
    ISceneGetHierarchyMcpInput,
    ISceneResolvePrefabRootUuidMcpInput,
    ISceneRestoreEditorResourceMcpInput,
    ISceneOpenMcpInput,
    ISceneSaveMcpInput,
    ISceneReloadMcpInput,
    ISceneQueryNodeMcpInput,
    ISceneFocusNodeMcpInput,
    ISceneCreateNodeMcpInput,
    IEditorSetSelectionMcpInput,
    IPrefabCreateFromNodeMcpInput,
    IPrefabInstanceOpMcpInput,
    IPrefabGetInfoMcpInput,
    IEditorMcpActionPlan,
    IEditorMcpActionResult,
    IEditorMcpCapabilityDescriptor,
    IEditorMcpOperationRequest,
    ILumenAssetSetMcpInput,
    ILumenBindClickMcpInput,
    ILumenBindSpriteMcpInput,
    ILumenBindSpriteBatchMcpInput,
    ILumenBindRefMcpInput,
    ILumenValidateRefsMcpInput,
    ILumenCommitMcpInput,
    ILumenCompAddMcpInput,
    ILumenCompRmMcpInput,
    ILumenCompSetMcpInput,
    ILumenCocosInfoMcpInput,
    ILumenInspectMcpInput,
    ILumenNodeAddMcpInput,
    ILumenNodeRenameMcpInput,
    ILumenNodeReorderMcpInput,
    ILumenNodeRmMcpInput,
    ILumenNodeSetMcpInput,
    ILumenPrefabMcpInput,
    ILumenRefreshMcpInput,
    ILumenScaffoldMcpInput,
    ILumenSchemaMcpInput,
    ILumenStructureMcpInput,
    ILumenCompileRecipeMcpInput,
    ILumenTemplatesMcpInput,
    ISnowbBmfontExportMcpInput,
} from './mcp/editor-mcp-contracts.js';
export { EditorMcpExecutionLaneResolver } from './mcp/editor-mcp-contracts.js';
export { ProductLineMcpPolicy, type ProductLineMcpDecision } from './mcp/product-line-mcp-policy.js';
export type { ContractPayload, IsoDateTimeString, PanelId, PluginId, PluginVersion, TaskId } from './shared/common-contracts.js';
export type {
    IPluginActivationManifest,
    IPluginDependencyManifest,
    IPluginEngineManifest,
    IPluginChangelogEntry,
    IPluginPackageFileIntegrity,
    IPluginPackageLibrary,
    IPluginPackageManifest,
    IPluginHealthSnapshot,
    IPluginManifest,
    IPluginPackageMeta,
    IPluginRuntimeMeta,
    IPluginRuntimeRecord,
    ILocalizedText,
    LocalizedText,
    PluginDeactivateReason,
    PluginKind,
    PluginState,
    PluginTrustLevel,
} from './plugin/plugin-contracts.js';
export type {
    ICleanupStepResult,
    IPluginFailureExport,
    IPluginFailureIncident,
    PluginFailurePhase,
} from './plugin/plugin-failure-contracts.js';
export type { IPluginDiagnosticEvent, IPluginDiagnosticExport, PluginDiagnosticSource } from './plugin/plugin-diagnostic-contracts.js';
export type {
    IPluginInstallPlan,
    IPluginInstallPlanStep,
    IPluginInstallResult,
    IPluginPackResult,
    IPluginPackageInspection,
    IPluginPackageValidationResult,
    IPluginRepairResult,
    IPluginUninstallResult,
    PluginInstallActionKind,
    PluginPackageOperationMode,
} from './plugin/plugin-package-operation-contracts.js';
