import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PRODUCT_ID = 'peanut.pod-lite';
const CREATOR_PROFILES = Object.freeze([
    Object.freeze({ version: '3.8.3', operationCount: 83, readOperationCount: 38, writeOperationCount: 45 }),
    Object.freeze({ version: '3.8.7', operationCount: 83, readOperationCount: 38, writeOperationCount: 45 }),
]);

const VERSION_TARGETS = Object.freeze([
    Object.freeze({ path: 'packages/engine/modules/creator-plugin/package.json', pattern: /("version"\s*:\s*")[^"]+(")/u }),
    Object.freeze({ path: 'packages/engine/modules/creator-plugin/peanut.pod-lite.manifest.json', pattern: /("version"\s*:\s*")[^"]+(")/u }),
    Object.freeze({ path: 'packages/hosts/modules/creator-38/package.json', pattern: /("version"\s*:\s*")[^"]+(")/u }),
]);

/**
 * @description 从根 package.json 读取 Lite 唯一发行版本。
 */
export function readRootReleaseVersion(repositoryRoot) {
    const rootPackage = JSON.parse(readFileSync(resolve(repositoryRoot, 'package.json'), 'utf8'));
    if (typeof rootPackage.version !== 'string' || !/^\d+\.\d+\.\d+$/u.test(rootPackage.version)) {
        throw new Error('lite_release_version_invalid');
    }
    return rootPackage.version;
}

/**
 * @description 生成或校验所有 Host/Core 版本镜像。
 */
export function synchronizeReleaseIdentity(repositoryRoot, check = false) {
    const version = readRootReleaseVersion(repositoryRoot);
    for (const target of VERSION_TARGETS) {
        const path = resolve(repositoryRoot, target.path);
        const current = readFileSync(path, 'utf8');
        if (!target.pattern.test(current)) {
            throw new Error(`lite_release_identity_target_invalid:${path}`);
        }
        const expected = current.replace(target.pattern, `$1${version}$2`);
        writeOrCheck(path, current, expected, check);
    }

    const manifestPath = resolve(repositoryRoot, 'packages/engine/modules/creator-plugin/peanut.pod-lite.manifest.json');
    const manifest = readFileSync(manifestPath, 'utf8');
    const hostVersionPattern = /("engines"\s*:\s*\{\s*"host"\s*:\s*")\^[^"]+(")/u;
    if (!hostVersionPattern.test(manifest)) {
        throw new Error(`lite_release_identity_target_invalid:${manifestPath}`);
    }
    const expectedManifest = manifest.replace(hostVersionPattern, `$1^${version}$2`);
    writeOrCheck(manifestPath, manifest, expectedManifest, check);

    const generatedPath = resolve(repositoryRoot, 'packages/engine/modules/creator-plugin/src/release-version.ts');
    const generated = renderReleaseVersion(version);
    const currentGenerated = readFileSync(generatedPath, 'utf8');
    writeOrCheck(generatedPath, currentGenerated, generated, check);
    return Object.freeze({ productId: PRODUCT_ID, version, creatorProfiles: CREATOR_PROFILES });
}

/**
 * @description 创建供后续 artifact builder 填充的稳定 Lite release descriptor。
 */
export function createLiteReleaseDescriptor(identity, sourceCommit, host, core) {
    if (identity?.productId !== PRODUCT_ID || typeof identity.version !== 'string' || !/^[a-f0-9]{40}$/u.test(sourceCommit)) {
        throw new Error('lite_release_identity_invalid');
    }
    return Object.freeze({
        schemaVersion: 1,
        productId: PRODUCT_ID,
        version: identity.version,
        sourceCommit,
        creatorProfiles: identity.creatorProfiles,
        host: validateArtifact(host, 'host'),
        core: validateArtifact(core, 'core'),
    });
}

function validateArtifact(value, kind) {
    if (value?.kind !== kind || typeof value.archive !== 'string' || typeof value.sha256 !== 'string' || !/^[a-f0-9]{64}$/u.test(value.sha256) || typeof value.packageDigest !== 'string' || !/^[a-f0-9]{64}$/u.test(value.packageDigest)) {
        throw new Error('lite_release_artifact_invalid');
    }
    return Object.freeze({ kind, archive: value.archive, sha256: value.sha256, packageDigest: value.packageDigest });
}

function writeOrCheck(path, current, expected, check) {
    if (current === expected) {
        return;
    }
    if (check) {
        throw new Error(`lite_release_identity_stale:${path}`);
    }
    writeFileSync(path, expected, 'utf8');
}

function renderReleaseVersion(version) {
    return `// Generated by tools/release-identity.mts from the root package.json.\n\n/** @description Peanut Pod Lite 的唯一发行版本。 */\nexport const PEANUT_POD_LITE_VERSION = '${version}';\n`;
}

if (process.argv[1] != null && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const repositoryRoot = resolve(import.meta.dirname, '..');
    const identity = synchronizeReleaseIdentity(repositoryRoot, process.argv.includes('--check'));
    process.stdout.write(`${JSON.stringify({ ok: true, ...identity }, null, 4)}\n`);
}
